
# Site settings
title: "Home" #"My Portfolio"
author: "Yahan Yang"
description: "A portfolio showcasing my work and projects."
remote_theme: "mmistakes/minimal-mistakes"

# Plugins (Required for Minimal Mistakes)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate

# GitHub Pages settings
baseurl: ""
url: "https://amber-y321.github.io"

# defaults:
#   - scope:
#       path: ""
#     values:
#       css: "/assets/css/custom.css"
defaults:
  - scope:
      path: ""
    values:
      css: "/assets/css/custom.css"
      
navigation:
  # - text: "Home"
  #   url: /
  - text: "Projects"
    url: /projects/
  - text: "About"
    url: /about/
  # - title: "Contact"
  #   url: /contact/
  # - title: "Blog"
  #   url: /blog/

author:
  name: "Yahan Yang"
  #avatar: "/assets/images/bio-photo.jpg"
  bio: "An **ENFJ** with a Bunch of Good Ideas." # Note: Markdown is allowed
  location: "Boston, MA"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://amber-y321.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amber-y321"

# Social Links
social:
  github: amber-y321
  # linkedin: 
  email: yangyahan0321@gmail.com



# Enable sidebar navigation
sidebar: 
  nav: "main"  # This references _data/navigation.yml
  title: "Yahan Yang"  # Sidebar title (Optional)
  description: "Data Analytics | Machine Learning | AI"
  social_links: true
  sticky: true
  show: true
  # avatar: "/assets/images/profile.jpg"  # Add a profile picture
