# Site settings
title: "My Portfolio"
author: "Yahan Yang"
description: "A portfolio showcasing my work and projects."
remote_theme: "mmistakes/minimal-mistakes"

# Plugins (Required for Minimal Mistakes)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate

# GitHub Pages settings
baseurl: ""
url: "https://amber-y321.github.io"

# ✅ Fix: Use `navigation:` instead of `nav:`
navigation:
  - text: "Home"
    url: /
  - text: "About"
    url: /about/
  - text: "Projects"
    url: /projects/
  #- text: "Contact"
  #  url: /contact/

# Social Links
social:
  github: amber-y321
  # linkedin: 
  email: yangyahan0321@gmail.com

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"  # ✅ Ensures all pages use the correct layout
      author_profile: true

# Enable sidebar navigation
sidebar: 
  nav: "main"  # This references _data/navigation.yml
  title: "Yahan Yang"  # Sidebar title (Optional)
  description: "Data Analytics | Machine Learning | AI"
  #avatar: "/assets/images/profile.jpg"  # Add a profile picture
  social_links: true  # Enable social media icons

