# Site settings
title: "My Portfolio"
author: "Yahan Yang"
description: "A portfolio showcasing my work and projects."
remote_theme: "mmistakes/minimal-mistakes"

# Plugins (Required for Minimal Mistakes)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate

# GitHub Pages settings
baseurl: ""
url: "https://amber-y321.github.io"

# ✅ Fix: Use `navigation:` instead of `nav:`
navigation:
  - text: "Home"
    url: /
  - text: "About"
    url: /about/
  - text: "Projects"
    url: /projects/
  #- text: "Contact"
  #  url: /contact/

# Social Links
social:
  github: amber-y321
  # linkedIn
  email: yangyahan0321@gmail.com
